//
// Generated file, do not edit! Created by opp_msgc 4.1 from ACK.msg.
//

#ifndef _ACK_M_H_
#define _ACK_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ACK.msg</tt> by opp_msgc.
 * <pre>
 * message ACK{
 *     string DesName;
 *     string SrcName;
 * }
 * </pre>
 */
class ACK : public ::cMessage
{
  protected:
    opp_string DesName_var;
    opp_string SrcName_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ACK&);

  public:
    ACK(const char *name=NULL, int kind=0);
    ACK(const ACK& other);
    virtual ~ACK();
    ACK& operator=(const ACK& other);
    virtual ACK *dup() const {return new ACK(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDesName() const;
    virtual void setDesName(const char * DesName_var);
    virtual const char * getSrcName() const;
    virtual void setSrcName(const char * SrcName_var);
};

inline void doPacking(cCommBuffer *b, ACK& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ACK& obj) {obj.parsimUnpack(b);}


#endif // _ACK_M_H_
