//
// Generated file, do not edit! Created by opp_msgc 4.1 from DATA.msg.
//

#ifndef _DATA_M_H_
#define _DATA_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>DATA.msg</tt> by opp_msgc.
 * <pre>
 * message DATA{
 *     string DesName;
 *     string SrcName;
 *     string Payload;
 * }
 * </pre>
 */
class DATA : public ::cMessage
{
  protected:
    opp_string DesName_var;
    opp_string SrcName_var;
    opp_string Payload_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DATA&);

  public:
    DATA(const char *name=NULL, int kind=0);
    DATA(const DATA& other);
    virtual ~DATA();
    DATA& operator=(const DATA& other);
    virtual DATA *dup() const {return new DATA(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDesName() const;
    virtual void setDesName(const char * DesName_var);
    virtual const char * getSrcName() const;
    virtual void setSrcName(const char * SrcName_var);
    virtual const char * getPayload() const;
    virtual void setPayload(const char * Payload_var);
};

inline void doPacking(cCommBuffer *b, DATA& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DATA& obj) {obj.parsimUnpack(b);}


#endif // _DATA_M_H_
