//
// Generated file, do not edit! Created by opp_msgc 4.1 from RREP.msg.
//

#ifndef _RREP_M_H_
#define _RREP_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>RREP.msg</tt> by opp_msgc.
 * <pre>
 * message RREP{
 *     string DesName;
 *    
 *    
 *     int cost;
 *    
 * }
 * </pre>
 */
class RREP : public ::cMessage
{
  protected:
    opp_string DesName_var;
    int cost_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RREP&);

  public:
    RREP(const char *name=NULL, int kind=0);
    RREP(const RREP& other);
    virtual ~RREP();
    RREP& operator=(const RREP& other);
    virtual RREP *dup() const {return new RREP(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDesName() const;
    virtual void setDesName(const char * DesName_var);
    virtual int getCost() const;
    virtual void setCost(int cost_var);
};

inline void doPacking(cCommBuffer *b, RREP& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RREP& obj) {obj.parsimUnpack(b);}


#endif // _RREP_M_H_
