//
// Generated file, do not edit! Created by opp_msgc 4.1 from RREQ.msg.
//

#ifndef _RREQ_M_H_
#define _RREQ_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>RREQ.msg</tt> by opp_msgc.
 * <pre>
 * message RREQ{
 *     string DesName;
 *     string SrcName;
 *     int cost;
 *     int timestamp;
 * }
 * </pre>
 */
class RREQ : public ::cMessage
{
  protected:
    opp_string DesName_var;
    opp_string SrcName_var;
    int cost_var;
    int timestamp_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RREQ&);

  public:
    RREQ(const char *name=NULL, int kind=0);
    RREQ(const RREQ& other);
    virtual ~RREQ();
    RREQ& operator=(const RREQ& other);
    virtual RREQ *dup() const {return new RREQ(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDesName() const;
    virtual void setDesName(const char * DesName_var);
    virtual const char * getSrcName() const;
    virtual void setSrcName(const char * SrcName_var);
    virtual int getCost() const;
    virtual void setCost(int cost_var);
    virtual int getTimestamp() const;
    virtual void setTimestamp(int timestamp_var);
};

inline void doPacking(cCommBuffer *b, RREQ& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RREQ& obj) {obj.parsimUnpack(b);}


#endif // _RREQ_M_H_
